name: EADSum
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10.12
  - cudatoolkit=12.4
  - pip
  - pip:
    - pytorch
    - torchvision
    - torchaudio
    - --index-url https://download.pytorch.org/whl/cu124
    - transformers
    - datasets
    - sentencepiece
    - protobuf
