name: EADSum
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10.12
  - pip
  - pip:
    - torch==2.4.1+cu124
    - torchvision==0.19.1+cu124 
    - torchaudio==2.4.1+cu124 
    - transformers==4.38.2
    - datasets
    - sentencepiece
    - protobuf
    - wandb
